version: '3.8'

services:
  ssk-substrate-playground:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./generated_code:/app/generated_code
    restart: unless-stopped
    env_file:
      - .env.dev
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    env_file:
      - .env.dev
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./init-scripts:/etc/localstack/init/ready.d/"
      - "./templates:/etc/app/templates/"