version: '3.8'

services:
  ssk-substrate-playground-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "3000:3000"
      - "9090:9090"
    restart: unless-stopped
    env_file:
      - .env.dev
    depends_on:
      localstack:
        condition: service_healthy

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - awslocal s3 ls
      interval: 5s
      timeout: 10s
      start_period: 10s
      retries: 5
    env_file:
      - .env.dev
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./init-scripts:/etc/localstack/init/ready.d/"
      - "./templates:/etc/app/templates/"
