name = "Pallet child bounties"

[metadata]
description = """
A pallet for managing child bounties within the governance system.
The Child Bounties pallet allows for the creation and management of child bounties tied to a parent bounty, including: child bounty creation, value management, and payout distribution."""
short_description = "FRAME child bounties pallet"
is_essential = false
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
categories = ["Governance"]
size = 10500
updated = "1729175503"

[runtime]
additional_pallet_impl_code = """

parameter_types! {
\tpub const MaxActiveChildBountyCount:u32=100;
    pub const ChildBountyValueMinimum: Balance=BountyValueMinimum::get()/10;
}
"""

[runtime.construct_runtime]
index = 20
runtime = ["ChildBounties", "pallet_child_bounties::Pallet<Runtime>"]

[runtime.pallet_traits]
ChildBountyValueMinimum = "ChildBountyValueMinimum"
WeightInfo = "pallet_child_bounties::weights::SubstrateWeight<Runtime>"
RuntimeEvent = "RuntimeEvent"
MaxActiveChildBountyCount = "MaxActiveChildBountyCount"

[dependencies]
required_pallets = ["Pallet bounties"]

[dependencies.pallet]
package = "pallet-child-bounties"
alias = "pallet child bounties"
default_features = false
git_repo = "https://github.com/paritytech/polkadot-sdk.git"
tag = "polkadot-v1.14.0"
