[package]
name = "pallets-configs"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
serde = "1.0"
tokio = "1.0"
warp = "0.3"
uuid = { version = "0.8", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
actix-web = "3.3.2"
time = "0.3"
regex = "1.10.6"