name = "Pallet Assets Freezer"

[metadata]
description = """Provides freezing features to `pallet-assets`"""
short_description = "FRAME Assets Freezer pallet"
is_essential = false
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
categorie = "Assets"
supported_template=["SoloChain","ParaChain","Minimal","Frontier","SoloFrontierChain"]
size = 10500
updated = "1729175503"


[runtime.construct_runtime]
runtime = ["AssetsFreezer", "pallet_assets_freezer::Pallet<Runtime>"]

[runtime.pallet_traits]
RuntimeFreezeReason = "RuntimeHoldReason" #"RuntimeFreezeReason"
RuntimeEvent = "RuntimeEvent"

[dependencies]
required_pallets = ["Pallet Assets"]

[dependencies.pallet]
package = "pallet-assets-freezer"
alias = "pallet assets freezer"
default_features = false
git_repo = "https://github.com/paritytech/polkadot-sdk.git"
tag = "polkadot-v1.14.0"
