name = "Pallet Asset Conversion"

[metadata]
description = """This pallet allows assets to be converted from one type to another by means of a constant product formula. The pallet based is based on Uniswap V2 logic.

Overview
This pallet allows you to:

create a liquidity pool for 2 assets
provide the liquidity and receive back an LP token
exchange the LP token back to assets
swap 2 assets if there is a pool created
query for an exchange price via a new runtime call endpoint
query the size of a liquidity pool.
"""
short_description = "FRAME Asset Conversion pallet"
is_essential = false
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
categories = ["Assets"]
size = 10500
updated = "1729175503"

[runtime]
additional_pallet_impl_code = """

parameter_types! {

	pub const AssetConversionPalletId: PalletId = PalletId(*b"py/ascon");
    pub const PoolSetupFee: Balance = 1 * DOLLARS; // should be more or equal to the existential deposit
	pub const MintMinLiquidity: Balance = 100;  // 100 is good enough when the main currency has 10-12 decimals.
	pub const LiquidityWithdrawalFee: Permill = Permill::from_percent(0);
	pub const Native: NativeOrWithId<u32> = NativeOrWithId::Native;

}


pub type NativeAndAssets =
	UnionOf<Balances, Assets, NativeFromLeft, NativeOrWithId<u32>, AccountId>;

"""
additional_runtime_lib_code = [
    "use frame_support::traits::fungible::NativeOrWithId;",
    "use frame_support::traits::fungible::UnionOf;",
    "use frame_support::traits::fungible::NativeFromLeft;",
    "use pallet_asset_conversion::Chain;",
    "use pallet_asset_conversion::WithFirstAsset;",
    "use pallet_asset_conversion::AccountIdConverter;",
    "use pallet_asset_conversion::Ascending;",
]

[runtime.construct_runtime]
runtime = ["AssetConversion", "pallet_asset_conversion::Pallet<Runtime>"]

[runtime.pallet_traits]
RuntimeEvent = "RuntimeEvent"
Balance = "<Self as pallet_balances::Config>::Balance"
HigherPrecisionBalance = "u128"
AssetKind = "NativeOrWithId<u32>"
Assets = "NativeAndAssets"
PoolId = "(Self::AssetKind, Self::AssetKind)"
PoolLocator = """Chain<
		WithFirstAsset<
			Native,
			AccountId,
			NativeOrWithId<u32>,
			AccountIdConverter<AssetConversionPalletId, Self::PoolId>,
		>,
		Ascending<
			AccountId,
			NativeOrWithId<u32>,
			AccountIdConverter<AssetConversionPalletId, Self::PoolId>,
		>,
	>"""
PoolAssetId = "u32" # "<Self as pallet_assets::Config<Instance2>>::AssetId"
#should be instance2
PoolAssets = "Assets"
# means 0.3%
LPFee = "ConstU32<3> "
PoolSetupFee = "PoolSetupFee"
PoolSetupFeeAsset = "Native"
PoolSetupFeeTarget = "()"                                                 #"ResolveAssetTo<AssetConversionOrigin, Self::Assets>"
LiquidityWithdrawalFee = "LiquidityWithdrawalFee"
MintMinLiquidity = "MintMinLiquidity"
MaxSwapPathLength = "ConstU32<4>"
PalletId = "AssetConversionPalletId"
WeightInfo = "pallet_asset_conversion::weights::SubstrateWeight<Runtime>"

[dependencies]
required_pallets = ["Pallet assets"]

[dependencies.pallet]
package = "pallet-asset-conversion"
alias = "pallet asset conversion"
default_features = false
git_repo = "https://github.com/paritytech/polkadot-sdk.git"
tag = "polkadot-v1.14.0"
