name = "Pallet Child Bounties"

[metadata]
description = """
A pallet for managing child bounties within the governance system.
The Child Bounties pallet allows for the creation and management of child bounties tied to a parent bounty, including: child bounty creation, value management, and payout distribution."""
short_description = "FRAME Child Bounties pallet"
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
category = "Governance"
supported_template = [
    "SoloChain",
    "ParaChain",
    "Minimal",
    "Frontier",
    "SoloFrontierChain",
]
size = 10500
updated = "1729175503"


# pub const MaxActiveChildBountyCount: u32 = 100;
[runtime.optional_parameter_types.MaxActiveChildBountyCount]
name = "MaxActiveChildBountyCount"
description = "The maximum number of active child bounties allowed."
prefix = "const"
p_type = "u32"
[runtime.optional_parameter_types.MaxActiveChildBountyCount.expression]
default_unit = ""
default_multiplier = 100
format = "{}{}"
possible_units = []
multiplier_configurable = true

# pub const ChildBountyValueMinimum: Balance = BountyValueMinimum::get() / 10;
[runtime.optional_parameter_types.ChildBountyValueMinimum]
name = "ChildBountyValueMinimum"
description = "The minimum value required to fund a child bounty, calculated as one-tenth of the parent bounty value."
prefix = "const"
p_type = "Balance"
[runtime.optional_parameter_types.ChildBountyValueMinimum.expression]
default_unit = ""
default_multiplier = 10
format = "BountyValueMinimum::get() / {}{}"
possible_units = []
multiplier_configurable = true


[runtime.construct_runtime]
runtime = ["ChildBounties", "pallet_child_bounties::Pallet<Runtime>"]

[runtime.pallet_traits]
MaxActiveChildBountyCount = "MaxActiveChildBountyCount"
ChildBountyValueMinimum = "ChildBountyValueMinimum"
WeightInfo = "pallet_child_bounties::weights::SubstrateWeight<Runtime>"
RuntimeEvent = "RuntimeEvent"

[dependencies]
required_pallets = ["Pallet Treasury", "Pallet Bounties", "Pallet Assets"]
# Assets is deep dependency

[dependencies.pallet]
package = "pallet-child-bounties"
alias = "pallet child bounties"
default_features = false
git_repo = "https://github.com/paritytech/polkadot-sdk.git"
tag = "polkadot-v1.14.0"
