name = "Pallet Collective"

[metadata]
description = "The Collective pallet allows a group of account IDs to make collective decisions through voting on proposals. Voting happens over a defined period, and a  member can influence the default vote. Proposals are executed once the required number of approvals is reached. "
short_description = "FRAME Collective pallet"
is_essential = false
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
category = "Governance"
supported_template=["SoloChain","ParaChain","Minimal","Frontier","SoloFrontierChain"]
size = 10500
updated = "1729175503"


# pub const CouncilMotionDuration: BlockNumber = 3 * MINUTES;
[runtime.optional_parameter_types.CouncilMotionDuration]
name = "CouncilMotionDuration"
description = "The duration of council motions, defined in blocks."
prefix = "const"
p_type = "BlockNumber"
[runtime.optional_parameter_types.CouncilMotionDuration.expression]
default_unit = "MINUTES"
default_multiiplier = 3
format = "{} * {}"
possible_units = ["MINUTES", "HOURS", "DAYS"]
multiplier_configurable = true

# pub const CouncilMaxProposals: u32 = 100;
[runtime.optional_parameter_types.CouncilMaxProposals]
name = "CouncilMaxProposals"
description = "The maximum number of proposals allowed in the council."
prefix = "const"
p_type = "u32"
[runtime.optional_parameter_types.CouncilMaxProposals.expression]
default_unit = ""
default_multiiplier = 100
format = "{}{}"
possible_units = []
multiplier_configurable = true

# pub const CouncilMaxMembers: u32 = 100;
[runtime.optional_parameter_types.CouncilMaxMembers]
name = "CouncilMaxMembers"
description = "The maximum number of members allowed in the council."
prefix = "const"
p_type = "u32"
[runtime.optional_parameter_types.CouncilMaxMembers.expression]
default_unit = ""
default_multiiplier = 100
format = "{}{}"
possible_units = []
multiplier_configurable = true

# pub MaxCollectivesProposalWeight: Weight = Perbill::from_percent(50) * BlockWeights::get().max_block;
[runtime.optional_parameter_types.MaxCollectivesProposalWeight]
name = "MaxCollectivesProposalWeight"
description = "The maximum weight of proposals for collectives, calculated as 50% of the maximum block weight."
prefix = "empty"
p_type = "Weight"
[runtime.optional_parameter_types.MaxCollectivesProposalWeight.expression]
default_unit = ""
default_multiiplier = 50
format = "{}Perbill::from_percent({}) * BlockWeights::get().max_block"
possible_units = []
multiplier_configurable = true


[runtime.construct_runtime]
runtime = ["Collective", "pallet_collective::Pallet<Runtime>"]

[runtime.pallet_traits]
MaxProposals = "CouncilMaxProposals"
MaxProposalWeight = "MaxCollectivesProposalWeight"
MotionDuration = "CouncilMotionDuration"
MaxMembers = "CouncilMaxMembers"
SetMembersOrigin = "EnsureRoot<Self::AccountId>"
RuntimeEvent = "RuntimeEvent"
WeightInfo = "pallet_collective::weights::SubstrateWeight<Runtime>"
RuntimeOrigin = "RuntimeOrigin"
DefaultVote = "pallet_collective::PrimeDefaultVote"
Proposal = "RuntimeCall"

[dependencies.pallet]
package = "pallet-collective"
alias = "pallet collective"
default_features = false
git_repo = "https://github.com/paritytech/polkadot-sdk.git"
tag = "polkadot-v1.14.0"
