name = "Pallet Timestamp"

[metadata]
description = """
The Timestamp pallet is designed to create a consensus-based time source. This helps ensure that nodes maintain a synchronized view of time that all network participants can agree on.
It defines an _acceptable range_ using a configurable constant to specify how much time must pass before setting the new timestamp. Validator nodes in the network must verify that the timestamp falls within this acceptable range and reject blocks that do not.
NOTE: The timestamp set by this pallet is the recommended way to query the onchain time instead of using block numbers alone. Measuring time with block numbers can cause cumulative calculation errors if depended upon in time critical operations and hence should generally be avoided."""
short_description = "FRAME Timestamp consensus pallet"
is_essential = ["SoloChain","SoloFrontierChain"]
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
category = "Consensus"
supported_template = [
    "SoloChain",
    "ParaChain",
    "Minimal",
    "Frontier",
    "SoloFrontierChain",
]
size = 5078
updated = "1729175503"
use_cases = ["Gaming", "NFT", "DeFi", "SupplyChain"]

[runtime.construct_runtime]
runtime = ["Timestamp", "pallet_timestamp"]

[runtime.pallet_traits]
OnTimestampSet = "Aura"
Moment = "u64"
MinimumPeriod = "ConstU64<{ SLOT_DURATION / 2 }>"
WeightInfo = "()"

[dependencies.pallet]
package = "pallet-timestamp"
alias = "pallet timestamp"
default_features = false
git_repo = "https://github.com/paritytech/polkadot-sdk.git"
tag = "polkadot-v1.14.0"
