name = "Pallet Indices"

[metadata]
description = """An index is a short form of an address. This module handles allocation of indices for a newly created accounts."""
short_description = "FRAME Indices pallet"
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
category = "Other"
supported_template=["SoloChain","ParaChain","Minimal","Frontier","SoloFrontierChain"]
size = 10500
updated = "1729175503"

# pub const IndexDeposit: Balance = 100 * CENTS;
[runtime.optional_parameter_types.IndexDeposit]
name = "IndexDeposit"
description = "The deposit required for registering an index, expressed in the smallest currency unit."
prefix = "const"
p_type = "Balance"
[runtime.optional_parameter_types.IndexDeposit.expression]
default_unit = "CENTS"
default_multiiplier = 100
format = "{} * {}"
possible_units = ["DOLLARS", "CENTS", "MILLICENTS"]
multiplier_configurable = true


[runtime.construct_runtime]
runtime = ["Indices", "pallet_indices::Pallet<Runtime>"]

[runtime.pallet_traits]
Deposit = "IndexDeposit"
RuntimeEvent = "RuntimeEvent"
Currency = "Balances"
WeightInfo = "pallet_indices::weights::SubstrateWeight<Runtime>"
AccountIndex = "u32"

[dependencies.pallet]
package = "pallet-indices"
alias = "pallet indices"
default_features = false
git_repo = "https://github.com/paritytech/polkadot-sdk.git"
tag = "polkadot-v1.14.0"
