name = "Pallet Transaction Payment"

[metadata]
description = """
This pallet provides the basic logic needed to pay the absolute minimum amount needed for a transaction to be included. This includes:
- _base fee_: This is the minimum amount a user pays for a transaction. It is declared as a base _weight_ in the runtime and converted to a fee using `WeightToFee`.
- _weight fee_: A fee proportional to amount of weight a transaction consumes.
- _length fee_: A fee proportional to the encoded length of the transaction.
- _tip_: An optional tip. Tip increases the priority of the transaction, giving it a higher chance to be included by the transaction queue.
The base fee and adjusted weight and length fees constitute the _inclusion fee_, which is the minimum fee for a transaction to be included in a block."""
short_description = "FRAME Transaction Payment pallet"
is_essential = ["SoloChain"]
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
category = "Consensus"
supported_template = [
    "SoloChain",
    "ParaChain",
    "Minimal",
    "Frontier",
    "SoloFrontierChain",
]
size = 5078
updated = "1729175503"
use_cases = ["Gaming", "NFT", "DeFi", "SupplyChain"]


[runtime]
additional_pallet_impl_code = """

parameter_types! {
    pub FeeMultiplier: Multiplier = Multiplier::one();
}

"""
# pub const FTPOperationalFeeMultiplier: u8 = 5;
[runtime.optional_parameter_types.FTPOperationalFeeMultiplier]
name = "FTPOperationalFeeMultiplier"
description = "The multiplier applied to operational fees for transactions."
prefix = "const"
p_type = "u8"

[runtime.optional_parameter_types.FTPOperationalFeeMultiplier.expression]
default_unit = ""
default_multiiplier = 5
format = "{}{}"
possible_units = []
multiplier_configurable = true

[runtime.construct_runtime]
runtime = ["TransactionPayment", "pallet_transaction_payment"]

[runtime.pallet_traits]
OnChargeTransaction = "FungibleAdapter<Balances, ()>"
WeightToFee = "IdentityFee<Balance>"
RuntimeEvent = "RuntimeEvent"
OperationalFeeMultiplier = "FTPOperationalFeeMultiplier"
LengthToFee = "IdentityFee<Balance>"
FeeMultiplierUpdate = "ConstFeeMultiplier<FeeMultiplier>"

[dependencies.pallet]
package = "pallet-transaction-payment"
alias = "pallet transaction payment"
default_features = false
git_repo = "https://github.com/paritytech/polkadot-sdk.git"
tag = "polkadot-v1.14.0"
