name = "Pallet Recovery"

[metadata]
description = "The Recovery pallet is an M-of-N social recovery tool for users to gain access to their accounts if the private key or other authentication mechanism is lost. Through this pallet, a user is able to make calls on-behalf-of another account which they have recovered. The recovery process is protected by trusted friends whom the original account owner chooses. A threshold (M) out of N friends are needed to give another account access to the recoverable account."
short_description = "FRAME Recovery pallet"
is_essential = false
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
categories = ["Accounts"]
supported_template=["SoloChain","ParaChain","Minimal","Frontier","SoloFrontierChain"]
size = 10500
updated = "1729175503"

# pub const ConfigDepositBase: Balance = 5 * DOLLARS;
[runtime.optional_parameter_types.ConfigDepositBase]
name = "ConfigDepositBase"
description = "The base deposit required for configuration."
prefix = "const"
p_type = "Balance"
[runtime.optional_parameter_types.ConfigDepositBase.expression]
default_unit = "DOLLARS"
default_multiiplier = 5
format = "{} * {}"
possible_units = ["DOLLARS", "CENTS", "MILLICENTS"]
multiplier_configurable = true

# pub const FriendDepositFactor: Balance = 50 * CENTS;
[runtime.optional_parameter_types.FriendDepositFactor]
name = "FriendDepositFactor"
description = "The deposit factor for each friend."
prefix = "const"
p_type = "Balance"
[runtime.optional_parameter_types.FriendDepositFactor.expression]
default_unit = "CENTS"
default_multiiplier = 50
format = "{} * {}"
possible_units = ["DOLLARS", "CENTS", "MILLICENTS"]
multiplier_configurable = true

# pub const MaxFriends: u16 = 9;
[runtime.optional_parameter_types.MaxFriends]
name = "MaxFriends"
description = "The maximum number of friends allowed."
prefix = "const"
p_type = "u16"
[runtime.optional_parameter_types.MaxFriends.expression]
default_unit = ""
default_multiiplier = 9
format = "{}{}"
possible_units = []
multiplier_configurable = true

# pub const RecoveryDeposit: Balance = 5 * DOLLARS;
[runtime.optional_parameter_types.RecoveryDeposit]
name = "RecoveryDeposit"
description = "The deposit required for account recovery."
prefix = "const"
p_type = "Balance"
[runtime.optional_parameter_types.RecoveryDeposit.expression]
default_unit = "DOLLARS"
default_multiiplier = 5
format = "{} * {}"
possible_units = ["DOLLARS", "CENTS", "MILLICENTS"]
multiplier_configurable = true


[runtime.construct_runtime]
runtime = ["Recovery", "pallet_recovery::Pallet<Runtime>"]

[runtime.pallet_traits]
ConfigDepositBase = "ConfigDepositBase"
FriendDepositFactor = "FriendDepositFactor"
MaxFriends = "MaxFriends"
RecoveryDeposit = "RecoveryDeposit"
RuntimeEvent = "RuntimeEvent"
WeightInfo = "pallet_recovery::weights::SubstrateWeight<Runtime>"
RuntimeCall = "RuntimeCall"
Currency = "Balances"


[dependencies.pallet]
package = "pallet-recovery"
alias = "pallet recovery"
default_features = false
git_repo = "https://github.com/paritytech/polkadot-sdk.git"
tag = "polkadot-v1.14.0"
