name = "Pallet Asset Conversion"

[metadata]
description = """This pallet allows assets to be converted from one type to another by means of a constant product formula. The pallet based is based on Uniswap V2 logic.

Overview
This pallet allows you to:

create a liquidity pool for 2 assets
provide the liquidity and receive back an LP token
exchange the LP token back to assets
swap 2 assets if there is a pool created
query for an exchange price via a new runtime call endpoint
query the size of a liquidity pool.
"""
short_description = "FRAME Asset Conversion pallet"
is_essential = false
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
categories = ["Assets"]
size = 10500
updated = "1729175503"

[runtime]
additional_pallet_impl_code = """

parameter_types! {

	pub const PoolSetupFee: Balance = 1000000000000; // should be more or equal to the existential deposit
	pub const MintMinLiquidity: Balance = 100;  // 100 is good enough when the main currency has 10-12 decimals.
	pub const LiquidityWithdrawalFee: Permill = Permill::from_percent(0);  // should be non-zero if AllowMultiAssetPools is true, otherwise can be zero.


}
"""

[runtime.construct_runtime]
runtime = ["Collective", "pallet_collective::Pallet<Runtime>"]

[runtime.pallet_traits]
RuntimeEvent = "RuntimeEvent"
Balance = "<Self as pallet_balances::Config>::Balance"
HigherPrecisionBalance = "u128"
AssetKind = ""
Assets = "Assets"
PoolId = ""
PoolLocator = ""
PoolAssetId = "u128"
PoolAssets = "Assets"
LPFee = "ConstU32<3> // means 0.3%"
PoolSetupFee = "PoolSetupFee"
PoolSetupFeeAsset = ""
PoolSetupFeeTarget = ""
LiquidityWithdrawalFee = "LiquidityWithdrawalFee"
MintMinLiquidity = "MintMinLiquidity"
MaxSwapPathLength = "ConstU32<4>"
PalletId = "AssetConversionPalletId"
WeightInfo = "pallet_asset_conversion::weights::SubstrateWeight<Test>"

[dependencies]
required_pallets = ["Pallet assets"]

[dependencies.pallet]
package = "pallet-asset-conversion"
alias = "pallet asset conversion"
default_features = false
git_repo = "https://github.com/paritytech/polkadot-sdk.git"
tag = "polkadot-v1.14.0"
