name = "GeneralCouncil Collective"

[metadata]
description = "The Collective pallet allows a group of account IDs to make collective decisions through voting on proposals. Voting happens over a defined period, and a  member can influence the default vote. Proposals are executed once the required number of approvals is reached. "
short_description = "FRAME Collective pallet"
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
categories = ["Governance"]
size = 10500
updated = "1729175503"
is_instance = true
supported_template = [
    "SoloChain",
    "ParaChain",
    "Minimal",
    "Frontier",
    "SoloFrontierChain",
]

# pub const GeneralCouncilMotionDuration: BlockNumber = 3 * MINUTES;
[runtime.optional_parameter_types.GeneralCouncilMotionDuration]
name = "GeneralCouncilMotionDuration"
description = "The duration of council motions, defined in blocks."
prefix = "const"
p_type = "BlockNumber"
[runtime.optional_parameter_types.GeneralCouncilMotionDuration.expression]
default_unit = "MINUTES"
default_multiplier = 3
format = "{} * {}"
possible_units = ["MINUTES", "HOURS", "DAYS"]
multiplier_configurable = true

# pub const GeneralCouncilMaxProposals: u32 = 100;
[runtime.optional_parameter_types.GeneralCouncilMaxProposals]
name = "GeneralCouncilMaxProposals"
description = "The maximum number of proposals allowed in the council."
prefix = "const"
p_type = "u32"
[runtime.optional_parameter_types.GeneralCouncilMaxProposals.expression]
default_unit = ""
default_multiplier = 100
format = "{}{}"
possible_units = []
multiplier_configurable = true

# pub const GeneralCouncilMaxMembers: u32 = 100;
[runtime.optional_parameter_types.GeneralCouncilMaxMembers]
name = "GeneralCouncilMaxMembers"
description = "The maximum number of members allowed in the council."
prefix = "const"
p_type = "u32"
[runtime.optional_parameter_types.GeneralCouncilMaxMembers.expression]
default_unit = ""
default_multiplier = 100
format = "{}{}"
possible_units = []
multiplier_configurable = true

# pub GeneralMaxCollectivesProposalWeight: Weight = Perbill::from_percent(50) * BlockWeights::get().max_block;
[runtime.optional_parameter_types.GeneralMaxCollectivesProposalWeight]
name = "GeneralMaxCollectivesProposalWeight"
description = "The maximum weight of proposals for collectives, calculated as 50% of the maximum block weight."
prefix = "empty"
p_type = "Weight"
[runtime.optional_parameter_types.GeneralMaxCollectivesProposalWeight.expression]
default_unit = ""
default_multiplier = 50
format = "{}Perbill::from_percent({}) * BlockWeights::get().max_block"
possible_units = []
multiplier_configurable = true


[runtime.construct_runtime]
runtime = ["Collective", "pallet_collective::Pallet<Runtime>"]

[runtime.pallet_traits]
MaxProposals = "GeneralCouncilMaxProposals"
MaxProposalWeight = "GeneralMaxCollectivesProposalWeight"
MotionDuration = "GeneralCouncilMotionDuration"
MaxMembers = "GeneralCouncilMaxMembers"
SetMembersOrigin = "EnsureRoot<Self::AccountId>"
RuntimeEvent = "RuntimeEvent"
WeightInfo = "pallet_collective::weights::SubstrateWeight<Runtime>"
RuntimeOrigin = "RuntimeOrigin"
DefaultVote = "pallet_collective::PrimeDefaultVote"
Proposal = "RuntimeCall"

[dependencies.pallet]
package = "pallet-collective"
alias = "pallet collective"
default_features = false
git_repo = "https://github.com/paritytech/polkadot-sdk.git"
tag = "polkadot-v1.14.0"
