name = "Pallet Transaction Storage"

[metadata]
description = """Indexes transactions and manages storage proofs. Allows storing arbitrary data on the chain. Data is automatically removed after StoragePeriod blocks, unless the storage is renewed. Validators must submit proof of storing a random chunk of data for block N - StoragePeriod when producing block N."""
short_description = "FRAME Transaction Storage pallet"
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
category = "Other"
supported_template = [
    "SoloChain",
    "ParaChain",
    "Minimal",
    "Frontier",
    "SoloFrontierChain",
]
size = 10500
updated = "1729175503"

[runtime]
# pub const PTSMaxBlockTransactions: u32 = 1000;
[runtime.optional_parameter_types.PTSMaxBlockTransactions]
name = "PTSMaxBlockTransactions"
description = "Maximum number of transactions allowed per block."
prefix = "const"
p_type = "u32"
[runtime.optional_parameter_types.PTSMaxBlockTransactions.expression]
default_unit = ""
default_multiplier = 1000
format = "{}{}"
possible_units = []
multiplier_configurable = true

# pub const PTSMaxTransactionSize: u32 = 1000;
[runtime.optional_parameter_types.PTSMaxTransactionSize]
name = "PTSMaxTransactionSize"
description = "Maximum size allowed for a single transaction in bytes."
prefix = "const"
p_type = "u32"
[runtime.optional_parameter_types.PTSMaxTransactionSize.expression]
default_unit = ""
default_multiplier = 1000
format = "{}{}"
possible_units = []
multiplier_configurable = true

[runtime.construct_runtime]
runtime = ["TransactionStorage", "pallet_transaction_storage::Pallet<Runtime>"]

[runtime.pallet_traits]
RuntimeCall = "RuntimeCall"
Currency = "Balances"
RuntimeEvent = "RuntimeEvent"
WeightInfo = "pallet_transaction_storage::weights::SubstrateWeight<Runtime>"
FeeDestination = "()"
RuntimeHoldReason = "RuntimeHoldReason"
MaxBlockTransactions = "PTSMaxBlockTransactions"
MaxTransactionSize = "PTSMaxTransactionSize"


[dependencies.pallet]
package = "pallet-transaction-storage"
alias = "pallet transaction storage"
default_features = false
git_repo = "https://github.com/paritytech/polkadot-sdk.git"
tag = "polkadot-v1.14.0"
