name = "Pallet Membership"

[metadata]
description = "Allows control of membership of a set of AccountIds, useful for managing membership of a collective. A prime member may be set."
short_description = "FRAME Membership pallet"
is_essential = false
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
category = "Governance"
supported_template=["SoloChain","ParaChain","Minimal","Frontier","SoloFrontierChain"]
size = 10500
updated = "1729175503"

# pub const TechnicalMaxMembers: u32 = 100;
[runtime.optional_parameter_types.TechnicalMaxMembers]
name = "TechnicalMaxMembers"
description = "The maximum number of members allowed in the technical committee."
prefix = "const"
p_type = "u32"
[runtime.optional_parameter_types.TechnicalMaxMembers.expression]
default_unit = ""
default_multiiplier = 100
format = "{}{}"
possible_units = []
multiplier_configurable = true


[runtime.construct_runtime]
runtime = ["Membership", "pallet_membership::Pallet<Runtime>"]

[runtime.pallet_traits]
MaxMembers = "TechnicalMaxMembers"
ResetOrigin = "EnsureRoot<AccountId>"
MembershipChanged = "()"
WeightInfo = "pallet_membership::weights::SubstrateWeight<Runtime>"
PrimeOrigin = "EnsureRoot<AccountId>"
RuntimeEvent = "RuntimeEvent"
AddOrigin = "EnsureRoot<AccountId>"
MembershipInitialized = "()"
SwapOrigin = "EnsureRoot<AccountId>"
RemoveOrigin = "EnsureRoot<AccountId>"

[dependencies.pallet]
package = "pallet-membership"
alias = "pallet membership"
default_features = false
git_repo = "https://github.com/paritytech/polkadot-sdk.git"
tag = "polkadot-v1.14.0"
