name = "Pallet Paged List"

[metadata]
description = """A thin wrapper pallet around a paged_list::StoragePagedList. It provides an API for a single paginated list. It can be instantiated multiple times to provide multiple lists."""
short_description = "FRAME Paged List pallet"
is_essential = false
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
categories = ["Other"]
size = 10500
updated = "1729175503"

[runtime.construct_runtime]
runtime = ["PagedList", "pallet_paged_list::Pallet<Runtime>"]

# pub const ValuesPerNewPage: u32 = 11;
[runtime.optional_parameter_types.ValuesPerNewPage]
name = "ValuesPerNewPage"
description = "The number of values per new page."
prefix = "const"
p_type = "u32"
[runtime.optional_parameter_types.ValuesPerNewPage.expression]
default_unit = ""
default_multiiplier = 11
format = "{}{}"
possible_units = []
multiplier_configurable = true


[runtime.pallet_traits]
Value = "u32"
ValuesPerNewPage = "ValuesPerNewPage"

[dependencies.pallet]
package = "pallet-paged-list"
alias = "pallet paged list"
default_features = false
git_repo = "https://github.com/paritytech/polkadot-sdk.git"
tag = "polkadot-v1.14.0"
