name = "Pallet Grandpa"

[metadata]
description = "This manages the GRANDPA authority set ready for the native code. These authorities are only for GRANDPA finality, not for consensus overall."
short_description = "FRAME Grandpa consensus pallet"
is_essential = ["SoloChain","SoloFrontierChain"]
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
category = "Consensus"
supported_template=["SoloChain","ParaChain","Minimal","Frontier","SoloFrontierChain"]
size = 5078
updated = "1729175503"

[runtime.construct_runtime]
runtime = ["Grandpa", "pallet_grandpa"]

# pub const MaxSetIdSessionEntries: u64 = 0;
[runtime.optional_parameter_types.MaxSetIdSessionEntries]
name = "MaxSetIdSessionEntries"
description = "The maximum number of session entries for a set ID."
prefix = "const"
p_type = "u64"
[runtime.optional_parameter_types.MaxSetIdSessionEntries.expression]
default_unit = ""
default_multiiplier = 0
format = "{}{}"
possible_units = []
multiplier_configurable = true

# pub const MaxAuthorities: u32 = 32;
[runtime.optional_parameter_types.MaxAuthorities]
name = "MaxAuthorities"
description = "The maximum number of authorities allowed."
prefix = "const"
p_type = "u32"
[runtime.optional_parameter_types.MaxAuthorities.expression]
default_unit = ""
default_multiiplier = 32
format = "{}{}"
possible_units = []
multiplier_configurable = true

# pub const MaxNominators: u32 = 0;
[runtime.optional_parameter_types.MaxNominators]
name = "MaxNominators"
description = "The maximum number of nominators allowed."
prefix = "const"
p_type = "u32"
[runtime.optional_parameter_types.MaxNominators.expression]
default_unit = ""
default_multiiplier = 0
format = "{}{}"
possible_units = []
multiplier_configurable = true


[runtime.pallet_traits]
MaxSetIdSessionEntries = "MaxSetIdSessionEntries"
MaxAuthorities = "MaxAuthorities"
MaxNominators = "MaxNominators"
RuntimeEvent = "RuntimeEvent"
WeightInfo = "()"
KeyOwnerProof = "sp_core::Void"
EquivocationReportSystem = "()"

[dependencies.pallet]
package = "pallet-grandpa"
alias = "pallet grandpa"
default_features = false
git_repo = "https://github.com/paritytech/polkadot-sdk.git"
tag = "polkadot-v1.14.0"
