name = "Pallet Utility"

[metadata]
description = '''
A stateless module with helpers for dispatch management which does no re-authentication.
This module contains two basic pieces of functionality:
- Batch dispatch: A stateless operation, allowing any origin to execute multiple calls in a single dispatch. This can be useful to amalgamate proposals, combining set_code with corresponding set_storages, for efficient multiple payouts with just a single signature verify, or in combination with one of the other two dispatch functionality.
- Pseudonymal dispatch: A stateless operation, allowing a signed origin to execute a call from an alternative signed origin. Each account has 2 * 2**16 possible "pseudonyms" (alternative account IDs) and these can be stacked. This can be useful as a key management tool, where you need multiple distinct accounts (e.g. as controllers for many staking accounts), but where it's perfectly fine to have each of them controlled by the same underlying keypair. Derivative accounts are, for the purposes of proxy filtering considered exactly the same as the origin and are thus hampered with the origin's filters.
Since proxy filters are respected in all dispatches of this module, it should never need to be filtered by any proxy.'''
short_description = "FRAME Utility pallet"
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
category = "Runtime"
supported_template = [
    "SoloChain",
    "ParaChain",
    "Minimal",
    "Frontier",
    "SoloFrontierChain",
]
size = 10500
updated = "1729175503"
use_cases = ["Gaming"]

[runtime.construct_runtime]
runtime = ["Utility", "pallet_utility::Pallet<Runtime>"]

[runtime.pallet_traits]
RuntimeEvent = "RuntimeEvent"
RuntimeCall = "RuntimeCall"
PalletsOrigin = "OriginCaller"
WeightInfo = "pallet_utility::weights::SubstrateWeight<Runtime>"

[dependencies.pallet]
package = "pallet-utility"
alias = "pallet utility"
default_features = false
git_repo = "https://github.com/paritytech/polkadot-sdk.git"
tag = "polkadot-v1.14.0"
