name = "Pallet Base Fee"

[metadata]
description = """Pallet Base Fee is a Substrate module that dynamically determines the base fee for EVM transactions in Frontier environments, similar to Ethereum’s EIP-1559 model. It automatically adjusts the base fee according to network load and gas demand, resulting in a more stable and fair cost structure for EVM-compatible Substrate chains"""
short_description = "FRAME Broker pallet"
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
is_essential = ["SoloFrontierChain"]
category = "Other"
supported_template = ["SoloFrontierChain"]
size = 10500
updated = "1729175503"

[runtime]
additional_pallet_impl_code = """

pub struct BaseFeeThreshold;
impl pallet_base_fee::BaseFeeThreshold for BaseFeeThreshold {
    fn lower() -> Permill {
        Permill::zero()
    }
    fn ideal() -> Permill {
        Permill::from_parts(500_000)
    }
    fn upper() -> Permill {
        Permill::from_parts(1_000_000)
    }
}

"""
# pub DefaultBaseFeePerGas: U256 = U256::from(1_000_000_000);
[runtime.optional_parameter_types.DefaultBaseFeePerGas]
name = "DefaultBaseFeePerGas"
description = "DefaultBaseFeePerGas is a parameter that sets the initial base fee for each unit of gas in EVM transactions (e.g., in a Frontier-based chain). It's the baseline cost from which dynamic mechanisms (like EIP-1559) adjust fees to maintain fair and stable transaction costs."
prefix = "empty"
p_type = "U256"
[runtime.optional_parameter_types.DefaultBaseFeePerGas.expression]
default_unit = ""
default_multiplier = 1_000_000_000
format = "U256::from({}{})"
possible_units = []
multiplier_configurable = true

# pub DefaultElasticity: Permill = Permill::from_parts(125_000);
[runtime.optional_parameter_types.DefaultElasticity]
name = "DefaultElasticity"
description = "DefaultElasticity is a parameter that defines how much the base fee can fluctuate between blocks. It represents the allowed flexibility or “elasticity” in adjusting fees to keep the network stable under varying transaction loads."
prefix = "empty"
p_type = "Permill"
[runtime.optional_parameter_types.DefaultElasticity.expression]
default_unit = ""
default_multiplier = 125_000
format = "Permill::from_parts({}{})"
possible_units = []
multiplier_configurable = true


[runtime.construct_runtime]
runtime = ["BaseFee", "pallet_base_fee::Pallet<Runtime>"]

[runtime.pallet_traits]
RuntimeEvent = "RuntimeEvent"
Threshold = "BaseFeeThreshold"
DefaultBaseFeePerGas = "DefaultBaseFeePerGas"
DefaultElasticity = "DefaultElasticity"


[dependencies.pallet]
package = "pallet-base-fee"
alias = "pallet base fee"
default_features = false
git_repo = "https://github.com/polkadot-evm/frontier"
tag = "polkadot-v1.14.0"
