name = "Pallet Multisig"

[metadata]
description = "This pallet contains functionality for multi-signature dispatch, a (potentially) stateful operation, allowing multiple signed origins (accounts) to coordinate and dispatch a call from a well-known origin, derivable deterministically from the set of account IDs and the threshold number of accounts from the set that must approve it. In the case that the threshold is just one then this is a stateless operation. This is useful for multisig wallets where cryptographic threshold signatures are not available or desired."
short_description = "FRAME Multisig pallet"
is_essential = false
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
categorie= "Governance"
supported_template=["SoloChain","ParaChain","Minimal","Frontier","SoloFrontierChain"]
size = 10500
updated = "1729175503"

[runtime.construct_runtime]
runtime = ["Multisig", "pallet_multisig::Pallet<Runtime>"]

# pub const DepositBase: u128 = 1 * 1000;
[runtime.optional_parameter_types.DepositBaseMultisig]
name = "DepositBaseMultisig"
description = "The base deposit required, expressed in the smallest currency unit."
prefix = "const"
p_type = "u128"
[runtime.optional_parameter_types.DepositBaseMultisig.expression]
default_unit = "1000"
default_multiiplier = 1
format = "{} * {}"
possible_units = ["1000"]
multiplier_configurable = true

# pub const DepositFactor: u128 = 1 * 1000;
[runtime.optional_parameter_types.DepositFactorMultisig]
name = "DepositFactorMultisig"
description = "The additional deposit required per unit of some factor, expressed in the smallest currency unit."
prefix = "const"
p_type = "u128"
[runtime.optional_parameter_types.DepositFactorMultisig.expression]
default_multiiplier = 1
default_unit = "1000"
format = "{}* {}"
possible_units = ["1000"]
multiplier_configurable = true

# pub const MaxSignatories: u32 = 20;
[runtime.optional_parameter_types.MaxSignatoriesMultisig]
name = "MaxSignatoriesMultisig"
description = "The maximum number of signatories allowed."
prefix = "const"
p_type = "u32"
[runtime.optional_parameter_types.MaxSignatoriesMultisig.expression]
default_unit = ""
default_multiiplier = 20
format = "{}{}"
possible_units = []
multiplier_configurable = true


[runtime.pallet_traits]
DepositBase = "DepositBaseMultisig"
DepositFactor = "DepositFactorMultisig"
MaxSignatories = "MaxSignatoriesMultisig"
Currency = "Balances"
RuntimeCall = "RuntimeCall"
RuntimeEvent = "RuntimeEvent"
WeightInfo = "pallet_multisig::weights::SubstrateWeight<Runtime>"

[dependencies.pallet]
package = "pallet-multisig"
alias = "pallet multisig"
default_features = false
git_repo = "https://github.com/paritytech/polkadot-sdk.git"
tag = "polkadot-v1.14.0"
