name = "Pallet Proxy"

[metadata]
description = "A pallet allowing accounts to give permission to other accounts to dispatch types of calls from their signed origin."
short_description = "FRAME Proxy pallet"
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
category = "Runtime"
supported_template = [
    "SoloChain",
    "ParaChain",
    "Minimal",
    "Frontier",
    "SoloFrontierChain",
]
size = 10500
updated = "1729175503"
use_cases = ["Gaming"]

[runtime]
additional_pallet_impl_code = """

parameter_types! {
\t// One storage item; key size 32, value size 8; .
\tpub const ProxyDepositBase: Balance = deposit(1, 8);
\t// Additional storage item size of 33 bytes.
\tpub const ProxyDepositFactor: Balance = deposit(0, 33);
\tpub const AnnouncementDepositBase: Balance = deposit(1, 8);
\tpub const AnnouncementDepositFactor: Balance = deposit(0, 66);
}

/// The type used to represent the kinds of proxying allowed.
#[derive(
\tCopy,
\tClone,
\tEq,
\tPartialEq,
\tOrd,
\tPartialOrd,
\tEncode,
\tDecode,
\tRuntimeDebug,
\tMaxEncodedLen,
\tscale_info::TypeInfo,
)]
pub enum ProxyType {
\tAny,
}
impl Default for ProxyType {
\tfn default() -> Self {
\t\tSelf::Any
\t}
}
impl InstanceFilter<RuntimeCall> for ProxyType {
\tfn filter(&self, _c: &RuntimeCall) -> bool {
\t\tmatch self {
\t\t\tProxyType::Any => true,
\t\t}
\t}
\tfn is_superset(&self, o: &Self) -> bool {
\t\tmatch (self, o) {
\t\t\t(x, y) if x == y => true,
\t\t\t(ProxyType::Any, _) => true,
\t\t}
\t}
}
"""
additional_runtime_lib_code = [
    "use codec::{Decode, Encode, MaxEncodedLen};",
    "use frame_support::traits::InstanceFilter;",
    "use sp_runtime::RuntimeDebug;",
]

[runtime.construct_runtime]
runtime = ["Proxy", "pallet_proxy::Pallet<Runtime>"]

# pub const MaxPending: u32 = 32;
[runtime.optional_parameter_types.MaxPending]
name = "MaxPending"
description = "The maximum number of pending items."
prefix = "const"
p_type = "u32"
[runtime.optional_parameter_types.MaxPending.expression]
default_unit = ""
default_multiiplier = 32
format = "{}{}"
possible_units = []
multiplier_configurable = true

# pub const MaxProxies: u32 = 32;
[runtime.optional_parameter_types.MaxProxies]
name = "MaxProxies"
description = "The maximum number of proxies allowed."
prefix = "const"
p_type = "u32"
[runtime.optional_parameter_types.MaxProxies.expression]
default_unit = ""
default_multiiplier = 32
format = "{}{}"
possible_units = []
multiplier_configurable = true


[runtime.pallet_traits]
MaxPending = "MaxPending"
MaxProxies = "MaxProxies"
CallHasher = "BlakeTwo256"
AnnouncementDepositBase = "AnnouncementDepositBase"
ProxyType = "ProxyType"
RuntimeCall = "RuntimeCall"
RuntimeEvent = "RuntimeEvent"
Currency = "Balances"
ProxyDepositBase = "ProxyDepositBase"
ProxyDepositFactor = "ProxyDepositFactor"
AnnouncementDepositFactor = "AnnouncementDepositFactor"
WeightInfo = "pallet_proxy::weights::SubstrateWeight<Runtime>"

[dependencies.pallet]
package = "pallet-proxy"
alias = "pallet proxy"
default_features = false
git_repo = "https://github.com/paritytech/polkadot-sdk.git"
tag = "polkadot-v1.14.0"
