name = "Pallet Sudo" #"pallet_sudo"

[metadata]
description = "A pallet to provide a way to execute privileged runtime calls using a specified sudo (“superuser do”) account."
short_description = "FRAME Sudo consensus pallet"
is_essential = ["SoloChain", "SoloFrontierChain"]
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
category = "Consensus"
supported_template = [
    "SoloChain",
    "ParaChain",
    "Minimal",
    "Frontier",
    "SoloFrontierChain",
]
size = 5078
updated = "1729175503"

[runtime.construct_runtime]
runtime = ["Sudo", "pallet_sudo"]

[runtime.pallet_traits]
RuntimeCall = "RuntimeCall"
RuntimeEvent = "RuntimeEvent"
WeightInfo = "pallet_sudo::weights::SubstrateWeight<Runtime>"

[dependencies.pallet]
package = "pallet-sudo"
alias = "pallet sudo"
default_features = false
git_repo = "https://github.com/paritytech/polkadot-sdk.git"
tag = "polkadot-v1.14.0"
