name = "Pallet Balances"

[metadata]
description = """
The Balances pallet provides functionality for handling accounts and balances for a single token.
It makes heavy use of concepts such as Holds and Freezes from the [`frame_support::traits::fungible`] traits, therefore you should read and understand those docs as a prerequisite to understanding this pallet."""
short_description = "FRAME Balances pallet"
is_essential = true
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
categorie = "Assets"
supported_template=["SoloChain","ParaChain","Minimal","Frontier","SoloFrontierChain"]
size = 5078
updated = "1729175503"

[runtime.construct_runtime]
runtime = ["Balances", "pallet_balances"]

# ! Leaving EXISTENTIAL_DEPOSIT as it is, because it is required to be imported in node/src/command.rs:10:41
[runtime]
additional_pallet_impl_code = """

/// Existential deposit.
pub const EXISTENTIAL_DEPOSIT: u128 = 500;

"""

# pub const MaxLocks: u32 = 50;
[runtime.optional_parameter_types.MaxLocks]
name = "MaxLocks"
description = "The maximum number of locks a single account can have."
prefix = "const"
p_type = "u32"

[runtime.optional_parameter_types.MaxLocks.expression]
default_unit = ""
default_multiiplier = 50
format = "{}{}"
possible_units = []
multiplier_configurable = true

[runtime.pallet_traits]
MaxLocks = "MaxLocks"
ExistentialDeposit = "ConstU128<500>"
MaxFreezes = "VariantCountOf<RuntimeFreezeReason>"
WeightInfo = "pallet_balances::weights::SubstrateWeight<Runtime>"
Balance = "Balance"
MaxReserves = "()"
ReserveIdentifier = "[u8; 8]"
RuntimeEvent = "RuntimeEvent"
DustRemoval = "()"
RuntimeHoldReason = "RuntimeHoldReason"
RuntimeFreezeReason = "RuntimeHoldReason"
AccountStore = "System"
FreezeIdentifier = "RuntimeFreezeReason"

[dependencies.pallet]
package = "pallet-balances"
alias = "pallet balances"
default_features = false
git_repo = "https://github.com/paritytech/polkadot-sdk.git"
tag = "polkadot-v1.14.0"
