name = "Pallet Node Authorization"

[metadata]
description = "The Node Authorization pallet allows for managing a whitelist of nodes authorized to produce blocks or participate in the network, ensuring only trusted nodes can operate within a permissioned Substrate network."
short_description = "FRAME Node Authorization pallet"
is_essential = false
compatibility = "Two"
license = "Apache-2.0"
authors = ["ParityTechnologies"]
categorie = "Runtime"
supported_template=["SoloChain","ParaChain","Minimal","Frontier","SoloFrontierChain"]
size = 10500
updated = "1729175503"


# pub const MaxWellKnownNodes: u32 = 8;
[runtime.optional_parameter_types.MaxWellKnownNodes]
name = "MaxWellKnownNodes"
description = "The maximum number of well-known nodes."
prefix = "const"
p_type = "u32"
[runtime.optional_parameter_types.MaxWellKnownNodes.expression]
default_unit = ""
default_multiiplier = 8
format = "{}{}"
possible_units = []
multiplier_configurable = true

# pub const MaxPeerIdLength: u32 = 128;
[runtime.optional_parameter_types.MaxPeerIdLength]
name = "MaxPeerIdLength"
description = "The maximum length for peer ID."
prefix = "const"
p_type = "u32"
[runtime.optional_parameter_types.MaxPeerIdLength.expression]
default_unit = ""
default_multiiplier = 128
format = "{}{}"
possible_units = []
multiplier_configurable = true


[runtime.construct_runtime]
runtime = ["NodeAuthorization", "pallet_node_authorization::Pallet<Runtime>"]

[runtime.pallet_traits]
MaxWellKnownNodes = "MaxWellKnownNodes"
MaxPeerIdLength = "MaxPeerIdLength"
RuntimeEvent = "RuntimeEvent"
AddOrigin = "EnsureRoot<AccountId>"
RemoveOrigin = "EnsureRoot<AccountId>"
SwapOrigin = "EnsureRoot<AccountId>"
ResetOrigin = "EnsureRoot<AccountId>"
WeightInfo = "()"


[dependencies.pallet]
package = "pallet-node-authorization"
alias = "pallet node authorization"
default_features = false
git_repo = "https://github.com/paritytech/polkadot-sdk.git"
tag = "polkadot-v1.14.0"
