name: Integration Tests

on:
  pull_request:
    branches:
      - '**'

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
  
        - name: Install Docker using Docker's official script
          run: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh
          continue-on-error: false
        - name: Install Docker Compose
          run: |
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              docker-compose --version
          continue-on-error: false
        - name: Build and up the test container
          run: |
            docker-compose -f docker-compose.test.yml up -d --build
        - name: Execute tests in the running services
          run: |
            docker-compose -f docker-compose.test.yml exec -T ssk-substrate-playground-test cargo test --test test_s3 -- --nocapture
        - name: Stop and remove the test container
          if: always()
          run: |
            docker-compose -f docker-compose.test.yml down