name: Deploy image to GHCR

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'
      # to be used by fork patch-releases ^^
      - 'v*.*.*-*'
  workflow_dispatch:
jobs:
    build-and-push:
      runs-on: ubuntu-latest
      steps:
        - name: Prepare
          id: prepare
          run: |
            TAG=${GITHUB_REF#refs/tags/}
            echo ::set-output name=tag_name::${TAG}

        - name: Checkout GitHub Action
          uses: actions/checkout@v2

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}

        - name: 'Build Inventory Image'
          run: |
            docker build . --tag ghcr.io/mvpworkshop/ssk-substrate-playground:${{steps.prepare.outputs.tag_name}} --tag ghcr.io/mvpworkshop/ssk-substrate-playground:latest
            docker push --all-tags ghcr.io/mvpworkshop/ssk-substrate-playground
